---
# Password-based SSH is used for initial bootstrap. After the first successful
# run, the macos_base role deploys your SSH public key to the openclaw user.
# You can then switch to key-based auth by removing ansible_ssh_pass and
# ansible_become_pass, and setting ansible_user to "openclaw".
all:
  hosts:
    mac-mini:
      ansible_host: "{{ vault_mac_mini_ip }}"
      ansible_user: "{{ vault_mac_mini_admin_user }}"
      ansible_ssh_pass: "{{ vault_mac_mini_admin_password }}"
      ansible_become_pass: "{{ vault_mac_mini_admin_password }}"
      ansible_connection: ssh
      ansible_python_interpreter: /usr/bin/python3
  vars:
    ansible_become_method: sudo
